# This is a sample Jupyter Notebook

Below is an example of a code cell. 
Put your cursor into the cell and press Shift+Enter to execute it and select the next one, or click 'Run Cell' button.

Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.

To learn more about Jupyter Notebooks in PyCharm, see [help](https://www.jetbrains.com/help/pycharm/ipython-notebook-support.html).
For an overview of PyCharm, go to Help -> Learn IDE features or refer to [our documentation](https://www.jetbrains.com/help/pycharm/getting-started.html).

上面是Pycharm自动创建的内容，在一本书里看到说“使用IDE的前提是你得知道它替你做了什么工作”

带着这个疑虑，我发现自己实际上现在并不完全知道IDE实际上干了什么，

但是我知道它做的这些工作没了它我依然能做，此之谓迷之自信，

于是接下来的工作便抛下对于效率工具的纠结，而义无反顾地朝着pytorch走去。

In [1]:
import torch # Windows平台的torch会依赖一个c++库，第一次运行报错，然后报错内容中跳出一个链接，点那个链接就能下载c++库，不得不再次感叹前人的工作实属伟大。

print("Hello World!")
print("Hello Pytorch!")

Hello World!
Hello Pytorch!


pytorch能干什么？最基础的是它作为“张量”的功能，或者说，Pytorch这个工具是面向张量的。

说是张量，实际上是高维矩阵的感觉。

下面展示了创建张量的方法。

## 创建张量

In [2]:
tensor1 = torch.Tensor([[1,2,3],[4,5,6],[7,8,9]]) # 指定数据 独特
torch.rand(3, 4) # 均匀分布3x4的矩阵
torch.randn(3, 4) # 正态分布
torch.ones(2, 2) # 全1矩阵
torch.zeros(5) # 全0矩阵
torch.eye(3) # 单位矩阵

print(f"同形状创建0: {torch.ones_like(tensor1)}") # 特别的like
print(f"同形状创建正态: {torch.randn_like(tensor1)}")

print(f"序列向量：{torch.arange(0, 10, 2)}")
print(f"间隔向量：{torch.linspace(0, 1, 5)}")

torch.empty(2, 3) # 空Tensor 速度快

torch.rand(3,4,5)

同形状创建0: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
同形状创建正态: tensor([[-0.3518, -0.2258, -0.9328],
        [ 1.1973,  1.1967,  0.2810],
        [-0.6118,  0.2083,  1.6679]])
序列向量：tensor([0, 2, 4, 6, 8])
间隔向量：tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


tensor([[[0.6821, 0.9730, 0.4697, 0.1855, 0.7065],
         [0.9155, 0.0104, 0.0680, 0.0458, 0.1672],
         [0.0433, 0.7736, 0.6876, 0.1876, 0.1612],
         [0.7780, 0.0851, 0.6414, 0.5783, 0.4943]],

        [[0.4224, 0.5992, 0.4666, 0.9647, 0.9477],
         [0.1516, 0.1021, 0.7142, 0.3251, 0.5272],
         [0.8428, 0.8626, 0.9882, 0.9835, 0.0380],
         [0.3724, 0.7892, 0.4767, 0.1280, 0.6878]],

        [[0.6057, 0.8016, 0.5999, 0.6201, 0.1668],
         [0.0404, 0.4640, 0.8885, 0.4860, 0.8520],
         [0.3153, 0.5924, 0.7995, 0.1664, 0.4602],
         [0.4169, 0.8026, 0.9359, 0.4172, 0.9851]]])

上方的代码块展示了如何创建各种形状的张量，可以创建确定的张量，也可以创建一些快捷张量

学会了如何创建张量之后，就会有迫切的欲望对张量进行一些操作，增删改查的想法在这里是合适的。

说是增删改查，研究对象可以是对整个表的结构，也可以是表中的值。

*首先我们从结构上来操作整张表，即，暂时只关心“维度”的问题*

增，就认为是增加维度。

删，就认为是删除维度。

改，就认为是更改某个维度的值。

查，查看张量的维度。

下面是对张量进行维度层面的增删改查的例子。

## 维度操作

In [3]:
tensor2 = torch.randn(2, 3)
print(tensor2)
print("查")
print(tensor2.shape) # 查看tensor的形状
print(tensor2 > 0) # 布尔掩码
print("增")
print(tensor2.unsqueeze(1).shape) # 指定位置扩展一个空维度
print("删")
print(tensor2.squeeze().shape) # 删除所有空维度（思考：为什么只能删除空维度？）
print("改")
print(tensor2[1, :].shape) # 从某个维度切片（想删某个维度，实际上就是把想留下的部分切片出来）
tensor2_1 = torch.randn(2, 4) # 一个张量维度扩展后，只有和其它张量拼在一起才能体现扩展的作用。
tensor2_2 = torch.randn(1, 3)
print(torch.cat([tensor2, tensor2_1], dim = 1).shape) # 保持其他维度不变，将第1维度的3和4拼起来
print(torch.cat([tensor2, tensor2_2], dim = 0).shape) # 将第0维度的2和1拼起来
print(tensor2.reshape(6, 1).shape) # 重新设置维度，注意元素个数保持不变
print(tensor2.permute(1, 0).shape) # 维度互换

tensor([[-0.7111,  0.0178,  0.2009],
        [ 0.4159,  0.9083, -0.2205]])
查
torch.Size([2, 3])
tensor([[False,  True,  True],
        [ True,  True, False]])
增
torch.Size([2, 1, 3])
删
torch.Size([2, 3])
改
torch.Size([3])
torch.Size([2, 7])
torch.Size([3, 3])
torch.Size([6, 1])
torch.Size([3, 2])


经过上面的维度体操，可以说已经掌握了对张量在宏观角度的操作。

在微观上，也就是说对张量中的值，也需要进行一些操作，但由于维度确定了，值的存在性也就确定了，对值的增删就没有了意义，所以只需要关注对值的“改、查”两个操作。

## 数值操作

In [4]:
tensor3 = torch.randn(2, 3, 4)
print(tensor3)
print("查")
print(tensor3.dtype) # tensor的元素的类型
print(tensor3[1, :].shape) # 从某个维度切片（切片这个行为，可以看作是高纬度的改，也可以看作是低维度的查）
print(tensor3[:,2].shape) # 从某个维度切片
print(tensor3>0) # 布尔掩码
print(tensor3[tensor3 > 0]) # 布尔掩码切片，会返回一个一维序列
print(tensor3[0,1][2]) # 直接索引查找是很灵活的
print(tensor3[0,1,2])
print(tensor3[[0,1],[0,2],:]) #相当于[0,0,:]和[1,2,:]
print("查统计数据")
print("平均数")
print(tensor3.mean())
print("中位数")
print(tensor3.median())
print("标准差")
print(tensor3.std())
print("最值")
print(tensor3.max())
print(tensor3.min())

print("改")
print("直接加法")
print(tensor3+1)
print("乘法")
print(tensor3.mul(10))
print("下面这个依然是数字乘法而不是矩阵乘法，但是对每个元素乘的权重不同，可以叫它权重乘法，会实现两个张量中相同位置上的值的运算")
print(tensor3.mul(tensor3))
print("原地操作")
print(tensor3.mul_(10))
print("张量乘法")
print("高维张量乘法的规则是，最后两个维度（最内部）需要符合矩阵乘法的规则(内标相同)，而其它维度需要相等或者可广播") # 可广播指的是维度为1
tensor3_1 = torch.randn(2,4,2).mul(10)
print("（同时伴随着一个类型转换操作）")
print((tensor3@(tensor3_1)).to(torch.int))



tensor([[[-1.9788, -0.6459, -1.1626, -0.9730],
         [ 0.4682, -1.0621, -0.9870, -1.5242],
         [-0.2596,  0.5855, -1.7444,  0.7711]],

        [[ 1.2049, -0.7256, -0.6298, -0.0086],
         [ 1.6113, -0.6415, -1.0569, -2.9428],
         [ 0.5425, -1.6116,  1.2211, -0.7645]]])
查
torch.float32
torch.Size([3, 4])
torch.Size([2, 4])
tensor([[[False, False, False, False],
         [ True, False, False, False],
         [False,  True, False,  True]],

        [[ True, False, False, False],
         [ True, False, False, False],
         [ True, False,  True, False]]])
tensor([0.4682, 0.5855, 0.7711, 1.2049, 1.6113, 0.5425, 1.2211])
tensor(-0.9870)
tensor(-0.9870)
tensor([[-1.9788, -0.6459, -1.1626, -0.9730],
        [ 0.5425, -1.6116,  1.2211, -0.7645]])
查统计数据
平均数
tensor(-0.5131)
中位数
tensor(-0.7256)
标准差
tensor(1.1254)
最值
tensor(1.6113)
tensor(-2.9428)
改
直接加法
tensor([[[-0.9788,  0.3541, -0.1626,  0.0270],
         [ 1.4682, -0.0621,  0.0130, -0.5242],
         [ 0.7404,  1.5855, -0.7

除了上面的“创建、操作维度、操作元素”，还有一个值得关注的方面是张量与硬件的关系。

张量如何保存到硬盘中？如何从硬盘中取出？

张量如何运行在CPU中或是GPU中？

## 硬件相关

In [5]:
tensor4 = torch.empty(2, 3)
print(tensor4.device) # 当前设备，CPU或者GPU
tensor4.to("cpu") # 改变设备，和类型转换是一个语法。

print(tensor4.requires_grad) # 查看自动求导状态，默认是关着的
print(tensor4.requires_grad_(True)) # 设置自动求导状态
print(tensor4.requires_grad_(False))
print(tensor4.requires_grad)

cpu
False
tensor([[2.3694e-38, 2.3694e-38, 2.3694e-38],
        [2.3694e-38, 2.3694e-38, 2.3694e-38]], requires_grad=True)
tensor([[2.3694e-38, 2.3694e-38, 2.3694e-38],
        [2.3694e-38, 2.3694e-38, 2.3694e-38]])
False


torch有它自己的特色，专门有利于AI领域的特色：对反向传播的支持
## 反向传播

In [6]:
tensor5=torch.arange(0,6).reshape(2,3).to(torch.float)
print("原数据")
print(tensor5)
print("打开自动求导：")
tensor5.requires_grad_(True)
print(tensor5)
tensor5m=torch.mean(tensor5.mul(tensor5))
print(f"求元素平方的平均值{tensor5m}")
print("反向传播前的梯度")
print(tensor5.grad)
tensor5m.backward()
print("反向传播后的梯度")
print(tensor5.grad)
print("梯度变了不会自动影响原数据")
print(tensor5)

原数据
tensor([[0., 1., 2.],
        [3., 4., 5.]])
打开自动求导：
tensor([[0., 1., 2.],
        [3., 4., 5.]], requires_grad=True)
求元素平方的平均值9.166666984558105
反向传播前的梯度
None
反向传播后的梯度
tensor([[0.0000, 0.3333, 0.6667],
        [1.0000, 1.3333, 1.6667]])
梯度变了不会自动影响原数据
tensor([[0., 1., 2.],
        [3., 4., 5.]], requires_grad=True)
